#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "plakar"
name = "Plakar"

description.en = "Encrypted, queryable backups"
description.fr = "Sauvegardes cryptées et interrogeables"

version = "1.0.3~ynh3"

maintainers = ["Lapineige"]

[upstream]
license = "ISC"
website = "https://plakar.io/"
demo = "https://demo.plakar.io/"
admindoc = "https://docs.plakar.io/"
userdoc = "https://docs.plakar.io/"
code = "https://github.com/PlakarKorp/plakar"

[integration]
yunohost = '>= 12.0.9'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/plakar"

    [install.init_main_permission]
    type = "group"
    default = "all_users"
    
    [install.encrypt]
    ask.en = "Do you want to encrypt your backups?"
    ask.fr = "Voulez-vous chiffrer vos sauvegardes ?"
    type = "boolean"
    default = true

    [install.encryption_passphrase]
    ask.en = "Set the password for encryption."
    ask.fr = "Définissez le mot de passe de chiffrement."
    help.en = "It's needed if you use backup encryption. You will need a strong enough password (or rather passphrase) for Plakar to accept it, allowing to install it."
    help.fr = "C'est nécessaire si vous utilisez le chiffrement. Vous aurez besoin d'un mot de passe (ou plutôt d'une phrase de passe) solide pour que Plakar la valide, permettant l'installation."
    type = "password"
    optional = true

    [install.default_yunohost_backup]
    ask.en = "Would you like to backup your YunoHost backups?"
    ask.fr = "Souhaitez-vous effectuer des sauvegardes des sauvegardes de YunoHost ?"
    type = "boolean"
    default = true

    [install.archivist_yunohost_backup]
    ask.en = "Would you like to backup Archivist (the YunoHost app) automated backups? (If so, it's recommended to set a similar frequency but delayed after archivist run)"
    ask.fr = "Souhaitez-vous effectuer des sauvegardes automatique d'Archivist (l'application YunoHost) ? (Si oui, il est recommandé de régler une fréquence similaire, mais décalée après le lancement d'Archivist)"
    type = "boolean"
    default = false

    [install.frequency]
    ask.en = "Choose the frequency of your backups?"
    ask.fr = "Choississez la fréquence de votre sauvegarde ?"
    type = "select"
    choices.daily = "Daily"
    choices.days_3 = "Each 3 days"
    choices.weekly = "Weekly"
    choices.weeks_2 = "Biweekly"
    choices.monthly = "Monthly"
    default = "weekly"

    [install.frequency_hour]
    ask.en = "Choose the time of the night to launch your backup"
    ask.fr = "Choississez l'heure de la nuit de lancement de votre sauvegarde"
    type = "select"
    choices.atmidnight = "Midnight"
    choices.at2am = "2am"
    choices.at3am = "3am"
    choices.at4am = "4am"
    choices.at6am = "6am"
    default = "at3am"
    
[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        extract = true
        amd64.url = "https://github.com/PlakarKorp/plakar/releases/download/v1.0.3-devel.d5a3fd0/plakar_1.0.3-devel.d5a3fd0_linux_amd64.tar.gz"
        amd64.sha256 = "3121ac62e39304a7e9494a95984d03469b097e4cb5988e00e3c3a095e62e20a0"
        arm64.url = "https://github.com/PlakarKorp/plakar/releases/download/v1.0.3-devel.d5a3fd0/plakar_1.0.3-devel.d5a3fd0_linux_arm64.tar.gz"
        arm64.sha256 = "a41d3dde35acd500d95a382dfd9da031a21016f555a344f60ad32f94f9e7fc65"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^*_linux_amd64.tar.gz"
        autoupdate.asset.arm64 = "^*_linux_amd64.tar.gz"

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.apt]
    packages = "ca-certificates"
