#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "plakar"
name = "Plakar"

description.en = "Backup solution powered by Kloset and ptar"
description.fr = "Backup solution powered by Kloset and ptar"

version = "1.0.2~ynh1"

maintainers = ["Lapineige"]

[upstream]
license = "ISC"
website = "https://plakar.io/"
demo = "https://demo.plakar.io/"
admindoc = "https://docs.plakar.io/"
userdoc = "https://docs.plakar.io/"
code = "https://github.com/PlakarKorp/plakar"

[integration]
yunohost = '>= 11.2.30'
helpers_version = "2.1"
# List of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386']
architectures = ["amd64", "arm64"]
multi_instance = false
ldap = "not_relevant"
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/plakar"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "all_users"
    
    [install.encrypt]
    ask.en = "Do you want to encrypt your backups ?"
    ask.fr = "Voulez-vous chiffrer vos sauvegardes ?"
    type = "boolean"
    default = true

    [install.encryption_passphrase]
    ask.en = "Set the password for encryption."
    ask.fr = "Définissez le mot de passe de chiffrement."
    help.en = "It's needed if you use backup encryption. You will need a strong enough password (or rather passphrase) for Plakar to accept it, allowing to install it."
    help.fr = "C'est nécessaire si vous utilisez le chiffrement. Vous aurez besoin d'un mot de passe (ou plutôt d'une phrase de passe) solide pour que Plakar la valide, permettant l'installation.""
    type = "password"
    optional = true

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those
    # https://yunohost.org/packaging_apps_resources

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/PlakarKorp/plakar/releases/download/v1.0.3-devel.455ca52/plakar_1.0.3-devel.455ca52_linux_amd64.deb"
        amd64.sha256 = "35ef1e3bc81930e668edea402c8093200c4731ba5e85eb6570d1ad3633ceeb56"
    
        arm64.url = "https://github.com/PlakarKorp/plakar/releases/download/v1.0.3-devel.455ca52/plakar_1.0.3-devel.455ca52_linux_arm64.deb"
        arm64.sha256 = "3b99a05a063ed996cc78d46bb8cdac734f4cc5dd470964d35bff8e7aa82c55c9"
    
        rename = "plakar.deb"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "^webmin_.*_all.deb$"

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $php_version setting as 8.3 (if php8.3-foobar dependencies are listed)
    packages = "ca-certificates, golang "

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir
