#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

_set_frequencies

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/plakar"

#=================================================
# HANDLE LOG FILES AND LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

# Create log directory
mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown $app -R /var/log/$app

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

# General default backup script
ynh_config_add --template="plakar_ynh_backups.sh" --destination="$install_dir/plakar_ynh_backups.sh"
chmod 700 "$install_dir/plakar_ynh_backups.sh"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Configuring $app's first backup repository in $data_dir..."

if [ $encrypt = true ]
then
  ynh_exec_as_app PLAKAR_PASSPHRASE=$encryption_passphrase $install_dir/plakar at $data_dir create
else
  ynh_exec_as_app $install_dir/plakar at $data_dir create -plaintext
  if ! [ -z $encryption_passphrase ]
  then
    encryption_passphrase='none'
  fi
fi
ynh_app_setting_set --key=encryption_passphrase --value="$encryption_passphrase"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

# SystemD services
# Main service
ynh_config_add_systemd --service="${app}_main_agent_and_webUI" --template="systemd.service"
yunohost service add "${app}_main_agent_and_webUI" --description="Encrypted, queryable backups - agent and WebUI" --log="/var/log/$app/$app.log"
# Remote server exposure
ynh_config_add_systemd --service="${app}_remote_server" --template="remote_server.service"
yunohost service add "${app}_remote_server" --description="Encrypted, queryable backups - remote backup server" --log="/var/log/$app/$app.log"

# Add Cron configuration file
if [ $default_yunohost_backup = true ]
then
  ynh_config_add --template="plakar_ynh_backups.cron" --destination="/etc/cron.d/${app}_ynh_backups"
  chown root: "/etc/cron.d/${app}_ynh_backups"
  chmod 644 "/etc/cron.d/${app}_ynh_backups"
  ynh_script_progression "Plakar is now configured to save your Yunohost backups on the defined regular rythm..."
fi

if [ $archivist_yunohost_backup = true ]
then
  ynh_config_add --template="plakar_archivist_backups.cron" --destination="/etc/cron.d/${app}_archivist_backups"
  chown root: "/etc/cron.d/${app}_archivist_backups"
  chmod 644 "/etc/cron.d/${app}_archivist_backups"
  ynh_script_progression "Plakar is now configured to save your backups made with Archivist on the defined regular rythm..."
fi


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting app's systemd service..."

ynh_systemctl --service="${app}_main_agent_and_webUI" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
