#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

_set_frequencies

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/plakar"

#=================================================
# HANDLE LOG FILES AND LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

# Create log directory
mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown $app -R /var/log/$app

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

# General default backup script
ynh_config_add --template="plakar.sh" --destination="$install_dir/plakar.sh"
chmod 700 "$install_dir/plakar.sh"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Configuring $app's first backup repository in $data_dir..."

if [ $encrypt = true ]
then
  ynh_exec_as_app PLAKAR_PASSPHRASE=$encryption_passphrase $install_dir/plakar at $data_dir create
else
  ynh_exec_as_app $install_dir/plakar at $data_dir create -plaintext
  #if not [ -z $encryption_passphrase ]
  #  $encryption_passphrase = 'none'
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

ynh_config_add_systemd

yunohost service add "$app" --description="Encrypted, queryable backups" --log="/var/log/$app/$app.log"

# Add Cron configuration file
ynh_config_add --template="plakar.cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
