#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
ynh_restore "$data_dir"

if ynh_in_ci_tests
then
	ynh_safe_rm $data_dir #Empty directory, but keep permissions
	mkdir $data_dir
	chown $app:$app $data_dir
	ynh_script_progression "Creating a repository again in $data_dir data directory [CI only]..."
	if [ $encrypt = true ]
	    then
	      ynh_exec_as_app PLAKAR_PASSPHRASE=$encryption_passphrase $install_dir/plakar at $data_dir create
	    else
	      ynh_exec_as_app $install_dir/plakar at $data_dir create -plaintext
	    fi
fi


#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app_main_agent_and_webUI.service"
systemctl enable "$app_main_agent_and_webUI.service" --quiet
ynh_restore "/etc/systemd/system/$app_remote_server.service"
systemctl enable "$app_remote_server.service" --quiet

yunohost service add "$app_main_agent_and_webUI" --description="Encrypted, queryable backups - agent and WebUI" --log="/var/log/$app/$app.log"
yunohost service add "$app_remote_server" --description="Encrypted, queryable backups - remote backup server" --log="/var/log/$app/$app.log"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"
# Make sure plakar can edit its log
touch /var/log/$app/$app.log
chown $app -R /var/log/$app

ynh_restore "/etc/cron.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
