#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd services..."

ynh_systemctl --service="$app_main_agent_and_webUI" --action="stop"
ynh_systemctl --service="$app_remote_server" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env plakar_ynh_backups.sh plakar_archivist_backups.sh "

chmod +x "$install_dir/plakar"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "${app}_main_agent_and_webUI" --description=Encrypted, queryable backups - agent and WebUI --log=/var/log/$app/$app.log
yunohost service add "${app}_remote_server" --description=Encrypted, queryable backups - remote backup server --log=/var/log/$app/$app.log 

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd services..."


ynh_systemctl --service="{app}_main_agent_and_webUI" --action="start"
ynh_systemctl --service="${app}_remote_server" --action="start"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
